# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NCU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NCU

  pod 'GoogleSignIn'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  
  pod 'Cartography'
  
  target 'NCUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NCUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
